---

apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $SERVICE_NAME
  template:
    metadata:
      labels:
        app: $SERVICE_NAME
    spec:
      restartPolicy: Always
      containers:
        - name: $SERVICE_NAME
          image: $IMAGE
          imagePullPolicy: Always
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: github-container-registry

---

apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
  labels:
    app: $SERVICE_NAME
spec:
  selector:
    app: $SERVICE_NAME
  ports:
    - name: service
      protocol: TCP
      port: 5000
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "${NAMESPACE}-${SERVICE_NAME}.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: $SERVICE_NAME
                port:
                  number: 5000
